config/routes.rb
Rails.application.routes.draw do
  get 'timelines/index'

  root 'pages#welcome'
  get 'pages/registered'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/testimonial'
  resources :microposts, only: [:create, :destroy] do
    resource :like, module: :microposts
  end
  resources :alerts
  resources :user_timelines, only: [:show]
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alert.rb
class Alert < ApplicationRecord
  belongs_to :user

  validates :symbol, presence: true, length: { maximum: 6 }
  validates :entry, presence: true, length: { maximum: 6 }
  validates :shares, length: { maximum: 6 }
  validates :stop, length: { maximum: 6 }
  validates :target, length: { maximum: 6 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :likes
  validates :user_id, presence: true
  validates :content, presence: true

  scope :by_most_recent, -> { order(created_at: :desc) }
  delegate :email, to: :user, prefix: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable

  enum registration_status: { pending: 0, registered: 1, expired: 2 }
  enum role: { standard: 0, admin: 1 }


  has_many :microposts, dependent: :destroy
  has_many :likes
  has_many :alerts

  def admin?
    role == 'admin'
  end

  def registered?
    role = 'registered'
  end

  def likes?(micropost)
    micropost.likes.where(user_id: id).any?
  end

  def active_for_authentication?
    super && self.registration_status == 'registered'
  end


end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def create
    @alert = current_user.alerts.build(alert_params)
    authorize @alert
    if @alert.save
      flash[:notice] = 'Alert Posted Successfully.'
      redirect_to timelines_index_path
    else
      @micropost = Micropost.new
      @microposts = Micropost.all
      @alerts = Alert.all
      render 'timelines/index', layout: 'timeline'
    end
  end

  def destroy
  end

  private
    def alert_params
      params.require(:alert).permit(:symbol, :entry, :stop, :target, :shares, :comment)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  include PunditConcerns
  protect_from_forgery with: :exception

  protected
    def after_sign_in_path_for(resource)
      timelines_index_path
    end
end

app/controllers/concerns/pundit_concerns.rb
module PunditConcerns
  extend ActiveSupport::Concern

  included do
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  end

  private
  def user_not_authorized
    self.response_body = nil
    flash[:alert] = 'A problem has occured.  Please email Admin if you feel this in error.'
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/microposts/likes_controller.rb
class Microposts::LikesController < ApplicationController
  before_action :set_micropost
  before_action :authenticate_user!

  def create
    @micropost.likes.where(user_id: current_user.id).first_or_create
    respond_to do |format|
      format.html { redirect_to timelines_index_path }
      format.js
    end
  end

  private
  def set_micropost
    @micropost = Micropost.find(params[:micropost_id])
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def create
    @micropost = current_user.microposts.build(micropost_params)
    authorize @micropost
    if @micropost.save
      flash[:notice] = 'Posted Successfully.'
      redirect_to timelines_index_path
    else
      @microposts = Micropost.all
      @alert = Alert.new
      @alerts = Alert.all
      render 'timelines/index', layout: 'timeline'
    end
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    authorize @micropost
    @micropost.destroy
    redirect_to timelines_index_path, notice: 'Post Deleted.'
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "page"
  before_action :authenticate_user!, only: :registered
  def welcome
  end

  def registered
  end

  def about
  end

  def testimonial
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
    if @user.persisted?
      UserMailer.account_registration(@user).deliver
      AdminMailer.user_register_notification.deliver
    end
  end

  protected

  def after_sign_up_path_for(resource)
    pages_registered_path
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  layout 'timeline'
  before_action :authenticate_user!
  def index
    @microposts = Micropost.by_most_recent
    @micropost = Micropost.new
    @alert = Alert.new
    @alerts = Alert.all
  end
end

app/controllers/user_timelines_controller.rb
class UserTimelinesController < ApplicationController
  before_action :authenticate_user!

  def show
    user = User.find(params[:id])
    @microposts = user.microposts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade show", role: 'alert') do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end

  def login_helper style = ''
    if current_user.is_a? User
      ' '.html_safe + (link_to 'Logout', destroy_user_session_path, method: :delete, class: style)
    else
      (link_to 'Sign up', new_user_registration_path, class: style) + ' '.html_safe +
      (link_to 'Login', new_user_session_path, class: style)
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def active? path
    "active" if current_page? path
  end

  def nav_items
    [
      {
        url: pages_contact_path,
        title: 'Contact'
      },
      {
        url: pages_about_path,
        title: 'About'
      },
      {
        url: pages_testimonial_path,
        title: 'Testimonials'
      }
    ]
end

  def links_helper tag_type, style
    nav_links = ''
    nav_items.each do |item|
      nav_links << "<a href='#{item[:url]}' class='#{style} #{active? item[:url]}'>#{item[:title]}</a>"
    end
    nav_links.html_safe
  end
end

app/helpers/timelines_helper.rb
module TimelinesHelper
  def delete_micropost_helper micropost
     if current_user.admin?
       link_to 'Delete', micropost, class: 'delete-post', method: :delete, data: { confirm: 'Are you sure?' }
     end
  end

  def liked?(micropost)
    'red' if current_user.likes?(micropost)
  end
end

app/helpers/user_timelines_helper.rb
module UserTimelinesHelper
end

app/views/alerts/_alert.html.erb
<div class="card" style="width: 95%;">
  <div class="card-block">
    <h4 class="card-title"><%= alert.symbol %>  Shares: <%= alert.shares %></h4>
    <p class="card-text">Price: <%= alert.entry %></p>
    <p>Notes About Trade.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
    <hr>
  </div>
</div>

app/views/alerts/_form.html.erb
<%= form_for @alert do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(@alert.errors.count, 'error') %> prohibited this post from being saved:</h5>
      <ul>
        <% @alert.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :symbol %>
  <%= f.text_field :symbol %> <br>
  <%= f.label :entry %>
  <%= f.text_field :entry %> <br>
  <%= f.label :stop %>
  <%= f.text_field :stop %> <br>
  <%= f.label :target %>
  <%= f.text_field :target %> <br>
  <%= f.label :shares %>
  <%= f.text_field :shares %> <br>
  <%= f.label :comment %>
  <%= f.text_area :comment %> <br>
  <%= f.submit 'Submit', class: 'btn btn-md btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeeThousand</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %>
    <%= yield %>
  </body>
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeeThousand</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash_messages %>
    <%= yield %>
  </body>
</html>

app/views/layouts/timeline.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bee Thousand</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'timelines', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash_messages %>
    <%= yield %>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_for @micropost, id: 'text-area-micropost' do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, 'error') %> prohibited this post from being saved:</h2>
      <ul>
        <% @micropost.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  <%= f.text_area :content, rows: 5, width: '' %> <br>
  <%= f.submit 'Submit', class: 'btn btn-md btn-primary' %>
<% end %>

app/views/microposts/_likes.html.erb
<%= link_to micropost_like_path(micropost), method: :post, remote: true do %>
  <%= fa_icon "heart", class: liked?(micropost) %>
<% end %>

app/views/microposts/_micropost.html.erb
<div class="row">
  <div class="col-md-12">
  <img src="http://placehold.it/50x50" alt="Gravatar" class='float-left'>
    <div class="talk-bubble tri-right left-top border">
      <div class="talktext">
        <ul>
          <li id=micropost-<%= dom_id(micropost) %>>
        </ul>

        <span><%= micropost.user_email %></span>
        <span>Post Time</span>
        <span id='likes'>  <%= render partial: 'microposts/likes', locals: { micropost: micropost } %></span>


        <%= delete_micropost_helper micropost %>
        </li>
        <p><%= micropost.content %></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <%= render 'shared/page_navbar' %>
    </div>
    <div class="container">
      This Will Become an About Page
    </div>

    <div class="inner cover">
      <p class="lead">
        <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
      </p>
    </div>
    <div class="cover-container">
      <div class="mastfoot">
        <div class="inner">
          <p>Disclaimer</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <%= render 'shared/page_navbar' %>>
    </div>

      <div class="container">
        <div class="row">
          <div class="col-md-12">
            Contact Page
          </div>
        </div>
      </div>

      <div class="inner cover">
        <p class="lead">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-lg btn-primary' %>
          <%= link_to 'Learn More', pages_about_path, class: 'btn btn-lg btn-secondary' %>
        </p>
      </div>
      <div class="cover-container">
        <div class="mastfoot">
          <div class="inner">
            <p>Disclaimer</p>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/pages/registered.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <%= render 'shared/page_navbar.html.erb' %>
    </div>

      <div class="container">
        <div class="row">
          <div class="col-md-12">
            Registration Pending
          </div>
        </div>
      </div>

      <div class="inner cover">
        <p class="lead">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-lg btn-primary' %>
          <%= link_to 'Learn More', pages_about_path, class: 'btn btn-lg btn-secondary' %>
        </p>
      </div>
      <div class="cover-container">
        <div class="mastfoot">
          <div class="inner">
            <p>Disclaimer</p>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/pages/testimonial.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <%= render 'shared/page_navbar' %>
    </div>

      <div class="container">
        <div class="row">
          <div class="col-md-12">
            Content
          </div>
        </div>
      </div>

      <div class="inner cover">
        <p class="lead">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-lg btn-primary' %>
          <%= link_to 'Learn More', pages_about_path, class: 'btn btn-lg btn-secondary' %>
        </p>
      </div>
      <div class="cover-container">
        <div class="mastfoot">
          <div class="inner">
            <p>Disclaimer</p>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/pages/welcome.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <%= render 'shared/page_navbar' %>
    </div>

      <div class="container">
        <div class="row">
          <div class="col-md-8">
            Video <br>
            <img src="http://placehold.it/600x400" alt="">

          </div>
          <div class="col-md-4">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, fugiat, ipsum. Ex officia illum suscipit ad mollitia tempora exercitationem aliquam iusto magni doloremque, nam dolor quibusdam nostrum quod, natus corporis.
          </div>
        </div>

        <div class="row">
          <div class="col-md-3">
            <img src="http://placehold.it/150x150" alt="">

          </div>
          <div class="col-md-9">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et doloremque, quasi! Odio, aliquid cupiditate pariatur recusandae consectetur veritatis consequuntur voluptates excepturi iure sequi nostrum eaque repellendus maiores saepe provident necessitatibus!
          </div>
        </div>
      </div>

      <div class="inner cover">
        <p class="lead">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-lg btn-primary' %>
          <%= link_to 'Learn More', pages_about_path, class: 'btn btn-lg btn-secondary' %>
        </p>
      </div>
      <div class="cover-container">
        <div class="mastfoot">
          <div class="inner">
            <p>Disclaimer</p>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/shared/_page_navbar.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Bee Thousand</h3>
    <nav class="nav nav-masthead">
    <%= links_helper '', 'nav-link' %>
    <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/timelines/_micropost.html.erb
<div class="row">
  <div class="col-md-12">
  <img src="http://placehold.it/50x50" alt="Gravatar" class='float-left'>
    <div class="talk-bubble tri-right left-top border">
      <div class="talktext">
        <li id="micropost-<%= dom_id(micropost) %>">
        <span><%= micropost.user_email %></span>
        <span>Post TIme</span>
        <span>Hearts</span>
        </li>
        <p><%= micropost.content %></p>
      </div>
    </div>
  </div>
</div>

app/views/timelines/index.html.erb
<header>
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="#">Hidden brand</a>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
    <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
  </nav>
</header>

<div class="row">
  <div class="col-md-9 col-offset-md-3">
    <%= render 'microposts/form', micros: @microposts %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 col-md-3 push-md-9">
    <%= render @alerts unless @alerts.nil? %>
    <div class="card" style="width: 95%;">
      <div class="card-block">
        <h4 class="card-title">Entry XYZ $20.01</h4>
        <p class="card-text">Shares: 100</p>
        <p>Notes About Trade.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
        <hr>
        <h3>New Trade Alert</h3>
        <%= render 'alerts/form', locals: { alert: @alert } if current_user.admin? %>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-9 pull-md-3">
    <ol class="microposts">
    <%= render @microposts %>
    </ol>
  </div>
</div>

app/views/user_timelines/show.html.erb
<h1>Future Home of a User Timeline</h1>
<% @microposts.each do |x| %>
  <%= x.content %>
<% end %>